name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Используем официальный готовый экшен от создателей Flet
      - name: Build Flet Android APK
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          python-version: '3.11'
          working-directory: '.'

      # Выкачиваем готовый результат
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: garage-calculator
          path: build/apk/*.apk

